			"routeros_ip_arps":      DatasourceIpArps(),
			"routeros_certificates": DatasourceCertificates(),
			"routeros_system_resource": DatasourceSystemResource(),
			"routeros_system_resource_cpus": DatasourceSystemResourceCpus(),
			"routeros_system_resource_irqs": DatasourceSystemResourceIrqs(),
			"routeros_system_resource_pcis": DatasourceSystemResourcePcis(),
			"routeros_system_routerboard": DatasourceSystemRouterboard(),
			"routeros_system_routerboard_settings": DatasourceSystemRouterboardSettings(),
